services:
    directus:
        image: directus/directus
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "replace-with-random-value"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "okcoolpap"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"

    opa:
        image: openpolicyagent/opa:1.1.0
        ports:
        - "8181:8181"
        volumes:
        - ./config-demo.yaml:/etc/opa/config.yaml
        - ./bundle:/bundle
        command: run --watch --disable-telemetry --server --log-level debug --log-format=json-pretty --addr :8181 --set default_decision=policies --ignore "*_test.rego" --config-file /etc/opa/config.yaml --bundle /bundle
        # opa run --watch --disable-telemetry --server --log-level debug --log-format=json-pretty --addr :8181 --set default_decision=policies --config-file ./config-demo.yaml --bundle ./bundle
